#!/bin/sh
source reconfig_meson

cd ~/sway-src/swaybg
git fetch
git checkout 1.0 
reconfig_meson
ninja -C build
ninja -C build install

DESTDIR=~/sway-debs/swaybg
mkdir -p $DESTDIR
DESTDIR=$DESTDIR ninja -C build install