#!/bin/sh

VERSION=0.8.1

cd ~/sway-src/wlroots
git fetch
git checkout $VERSION

reconfig_meson
ninja -C build
ninja -C build install
ldconfig

DEBVER=1
DEB=wlroots-$VERSION-$DEBVER
DESTDIR=~/sway-debs/$DEB
mkdir -p $DESTDIR
DESTDIR=$DESTDIR ninja -C build install

mkdir -p $DESTDIR/DEBIAN

